repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict

# this validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.0
  hooks:
    - id: check-github-workflows
