on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


name: Render and Publish

jobs:

  code-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install pre-commit
          pre-commit install

      - name: Run pre-commit
        run: |
          pre-commit run --all-files --show-diff-on-failure


  build-deploy:
    runs-on: ubuntu-latest
    needs: code-style
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Check Quarto version
        run: |
          quarto --version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          quarto install extension . --no-prompt
          python3 -m pip install jupyter

      - name: Render book
        run: |
          quarto render cheatsheet.qmd --to cheatsheet-pdf

      # publish only when the main branch is updated
      - name: Publish
        # if: github.ref == 'refs/heads/main'
        uses: quarto-dev/quarto-actions/publish@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
