on:
  pull_request:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


name: CI

jobs:

  code-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python3 -m pip install pre-commit
          pre-commit install

      - name: Run pre-commit
        run: |
          pre-commit run --all-files --show-diff-on-failure

  create-archives:
    runs-on: ubuntu-latest
    needs: code-style
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install zip gzip tar -y

      - name: Create archive
        run: |
          zip -r cheatsheet.zip _extensions
          tar -czvf cheatsheet.tar.gz _extensions

      - name: List files
        run: |
          ls -l

      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          path: |
            cheatsheet.zip
            cheatsheet.tar.gz

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Check Quarto version
        run: |
          quarto --version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          quarto add cheatsheet.tar.gz --no-prompt
          python3 -m pip install jupyter

      - name: Render book
        run: |
          quarto render cheatsheet.qmd --to cheatsheet-pdf

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: create-archives
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Relase to github
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cheatsheet.zip
            cheatsheet.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
